CREATE SCHEMA MUSIQUE_DB AUTHORIZATION SA;

use MUSIQUE_DB;

CREATE TABLE artist (
    id   INTEGER   PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    bio VARCHAR(255),
    fan_number INTEGER
);